name: Node.js CI

on: [push]

jobs:
  testing-backend:
    name: Run backend tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
      - name: RUN unit test
        run: |
          cd ./backend
          npm ci
          npm run test
  testing-frontend:
    name: Run frontend tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
      - name: RUN unit test
        run: |
          cd ./frontend
          npm ci
          npm run test
